### ISSUE TITLE
Discovery Failed with Fortigate VE with VDOMs

### ISSUE THREAD

**Issue by Costya-Y** [QualiSystems/FortiGate-FortiOS-Firewall-Shell-2G#3]
Shell unable to autoload Fortigate with VDOMs configured.

**Comment by saklar13** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [first](https://trello.com/c/TMR668pN/1-first)

**Comment by saklar13** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [first](https://trello.com/c/TMR668pN/1-first)

**Comment by saklar13** [comment]
Fixed in [cloudshell-firewall-fortinet 1.1.1](https://github.com/QualiSystems/cloudshell-firewall-fortinet/releases/tag/1.1.1)
