### ISSUE TITLE
Autoload fails in offline mode

### ISSUE THREAD

**Issue by turkovda** [QualiSystems/FortiGate-FortiOS-Firewall-Shell-2G#4]
### Issue details

Autoload fails in offline mode with error:
![image](https://user-images.githubusercontent.com/59359491/87693973-47180600-c796-11ea-8ab8-599a168cd826.png)

### Logs
[InstallRequirements_81773.log](https://github.com/QualiSystems/FortiGate-FortiOS-Firewall-Shell-2G/files/4932642/InstallRequirements_81773.log)

### Steps to reproduce

1. Download and unpack dependencies to local repository
2. Create resource 

### Actual Result

Autoload failed

**Comment by saklar13** [comment]
I updated offline dependencies and now it works

**Comment by turkovda** [comment]
Verified.
